Repository uwblueprint/community-fridge-kw, pull requests merged in 2021-09, with the labels that each got.

#1 build: add commitlint and husky dependencies
  .commitlintrc.json
  .husky/commit-msg
  .huskyrc.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/APIClients/EntityAPIClient.ts
  frontend/yarn.lock
  package.json
  yarn.lock
Labels: infra/devops, ready for review

#2 build: setup github actions ci
  .github/workflows/ci.yml
  backend/typescript/migrate.js
  backend/typescript/models/entity.model.ts
  backend/typescript/models/index.ts
  backend/typescript/rest/userRoutes.ts
  backend/typescript/services/implementations/__tests__/userService.test.ts
  backend/typescript/services/implementations/authService.ts
  backend/typescript/services/implementations/entityService.ts
  backend/typescript/services/implementations/fileStorageService.ts
  backend/typescript/services/implementations/userService.ts
  backend/typescript/testUtils/testDb.ts
Labels: infra/devops, ready to merge

#3 docs: update README
  README.md
Labels: changes requested

#8 chore: add github actions to check PR Title
  .github/workflows/lint-pr.yml
Labels: infra/devops

#6 build: set up Vault config and scripts
  hooks/post-merge
  secret.config
  setup.sh
Labels: infra/devops
